name: Atualizar Estatísticas do README

on:
  schedule:
    - cron: "*/30 * * * *"  # executa a cada 30 minutos
  workflow_dispatch: # permite rodar manualmente
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Atualizar README (forçar atualização do cache)
        run: |
          sed -i "s/cacheBuster=.*/cacheBuster=$(date +%s)/" README.md || true

      - name: Commit e Push das alterações
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Atualização automática do README"
          git push
